UPDATE pkghead SET pkghead_indev = true WHERE pkghead_name = 'te';
DELETE FROM metasql WHERE metasql_group = 'te' AND metasql_name = 'addsheet' AND metasql_grade =0;
DELETE FROM metasql WHERE metasql_group = 'te' AND metasql_name = 'addteprj' AND metasql_grade =0;
DELETE FROM metasql WHERE metasql_group = 'te' AND metasql_name = 'addteprjtask' AND metasql_grade =0;
DELETE FROM metasql WHERE metasql_group = 'te' AND metasql_name = 'editsheet' AND metasql_grade =0;
DELETE FROM metasql WHERE metasql_group = 'te' AND metasql_name = 'getsheet' AND metasql_grade =0;
DELETE FROM metasql WHERE metasql_group = 'te' AND metasql_name = 'addtecustrate' AND metasql_grade=0;
DELETE FROM metasql WHERE metasql_group = 'te' AND metasql_name = 'addteemprate' AND metasql_grade=0;
DELETE FROM metasql WHERE metasql_group = 'te' AND metasql_name = 'gettask' AND metasql_grade=0;
UPDATE pkghead SET pkghead_indev = false WHERE pkghead_name = 'te';